const AllProjectData = [
    {
        id: "8765349",
        title: "Stayz | A Booking Website",
        description: "Find, compare, and reserve your ideal hotel.",
        features: [
            "Developing a travel app enabling users to search for hotels and save favorite destinations.",
            "Enhanced the app's user experience with a responsive interface using Tailwind CSS.",
            "Will Implemente a search feature using Next Js",
            "Implemented a user authentication system using Clerk Auth and MongoDB.",
            "Implemented features for seamless browsing, profile management, and date selection.",
        ],
        github: "",
        url: "https://stayz.vercel.app",
        imageSrc: "/images/project-image/stayz.vercel.app.jpg",
        tags: ["Next Js", "Javascript", "Clerk Auth", "Mongo DB", "Tailwind", "shadcn/ui", "Swiper Js",],
        start: "January-2024",
        end: "",
        ongoing: true,
    },
    {
        id: "3931151",
        title: "E-Commerce Website",
        description: "E-Commerce Web app built using Django",
        features: [
            "Crafted a fully functional e-commerce web application using Django.",
            "Provided a user-friendly shopping experience with product browsing, cart management.",
            "Utilized Django’s views, models, and middlewares for efficient performance.",
        ],
        github: "hhttps://github.com/Swastikdan/E-Commerce-Django",
        url: "https://swastikpyprojects.pythonanywhere.com/",
        imageSrc: "/images/project-image/swastikpyprojects.pythonanywhere.com.jpg",
        tags: ["Django", "Tailwind", "JavaScript", "SQLite", "Python", "Swiper Js"],
        start: "May-2023",
        end: "June-2023",
        ongoing: false,
    },
    {
        id: "4677491",
        title: "Recipe Seeker Webapp",
        description: "A web app where users can search for recipes.",
        features: [
            "Developed an Express web application backed by MongoDB for effortless recipe discovery.",
            "Added features for searching recipes by name or ingredients, applying filters based on time and difficulty, and accommodating dietary restrictions.",
        ],
        github: "https://github.com/Swastikdan/Racipe-Seeker-App",
        url: "https://racipe-seeker.swastikdan.in/",
        imageSrc: "/images/project-image/racipe-seeker.swastikdan.in.png",
        tags: ["Node Js", "Express Js", "Mongo DB", "Tailwind", "JavaScript"],
        start: "August-2023 ",
        end: "September-2023",
        ongoing: false,
    },

    {
        id: "6477128",
        title: "Random Jokes API",
        description:
            "A RESTful API offering access to a vast collection of 400,000+ jokes.",
        features: [
            "Created a RESTful API using Flask, offering access to a vast collection of 400,000+ jokes.",
        ],
        github: "https://github.com/Swastikdan/Random-Jokes-Api",
        url: "https://jokemasterapi.vercel.app/api/jokes",
        imageSrc: "/images/project-image/jokemasterapi.vercel.app.png",
        tags: ["Flask", "SQLite"],
        start: "April-2023",
        end: "June-2023",
        ongoing: false,
    },
    {
        id: "750369",
        title: "Film Fanatic Website",
        description: "A movie data display website with TMDB api.",
        features: [
            "Built a movie website using TMDb API for users to search, view, and discover movies.",
            "Currently developing a movie and series data display website utilizing the TMDB API.",
        ],
        github: "https://github.com/Swastikdan/Film-Fanatic",
        url: "https://film-fanatic.vercel.app/",
        imageSrc: "/images/project-image/film-fanatic.vercel.app.jpg",
        tags: ["Node Js", "JavaScript", "Tailwind", "TMDB API"],
        start: "April-2023",
        end: "",
        ongoing: true,
    },
    {
        id: "8958100",
        title: "Random Password Generator",
        description: "Generate strong & secure passwords online.",
        features: [
            "Generates random passwords",
            "Allows customization of password length and complexity",
        ],
        github: "https://github.com/Swastikdan/Random-Password-Generator",
        url: "https://random-password-creator.vercel.app/",
        imageSrc: "/images/project-image/random-password-creator.vercel.app.png",
        tags: ["JavaScript", "Vite Js", "Tailwind"],
        start: "April-2023",
        end: "April-2023",
        ongoing: false,
    },
    {
        id: "9290167",
        title: "Netflix Clone (Front End)",
        description: "A clone of the Netflix website.",
        features: [
            "Replicates Netflix's user interface",
            "Features popular Netflix shows on homepage",
        ],
        github: "https://github.com/Swastikdan/Netflix-Clone",
        url: "https://tooin.vercel.app/",
        imageSrc: "/images/project-image/tooin.vercel.app.jpg",
        tags: ["JavaScript", "Vite Js", "Tailwind"],
        Date: "June-2022",
        Date: "July-2022",
        ongoing: false,
    },
].map(project => ({
    ...project,
    projecturl: project.title.toLowerCase().split(' ').join('-')
  }));
  
  export default AllProjectData;