import { Pathway_Extreme } from "next/font/google";
import "./globals.css";

const pathwayextreme = Pathway_Extreme({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import NavBar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${pathwayextreme.className} overflow-y-auto scroll-smooth bg-gray-950 text-white `}
      >
  
        <main >
          <NavBar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
